name: my-first-job
on: 
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-name
        run: echo "My name is Murali"
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: fetch meta data
        run: echo "${{toJson(github)}}"
  second-job:
    runs-on: ubuntu-latest
    needs: [first-job,metadata]
    steps:
      - name: print-my-designation
        run: echo "I am a DevOps Engineer"
